spring:
  application:
    name: Schedular-service

server:
  port: 8081

lichess:
  base-url: ${LICHESS_BASE_URL:https://lichess.org/api}
#  token: ${LICHESS_TOKEN}

cds:
  base-url: ${CDS_BASE_URL}
